name: gan-website
static_sites:
  - name: gan-frontend
    source_dir: /
    github:
      repo: ezaldin-khaled/GAN7
      branch: main
    build_command: npm install && npm run build
    output_dir: dist
    routes:
      - path: /
    environment_slug: static-site
    envs:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://api.gan7club.com:8000
      - key: VITE_STRIPE_PUBLIC_KEY
        value: pk_test_51RfHRzP623EsFG0oJiJ43PsCwsWyguGY7yoYuvMiUMMVyU019qUzMDytg7JOIx6k7EXxSOf36jTHnvbBjukMAFDy00iQcjXEOc
      - key: VITE_APP_NAME
        value: Gan7Club
      - key: VITE_APP_VERSION
        value: 1.0.0
    domains:
      - name: gan7club.com
      - name: www.gan7club.com
    # Explicitly specify this is a static site
    run_command: ""
    instance_count: 0 