name: gan-website
static_sites:
  - name: gan-frontend
    source_dir: /
    github:
      repo: ezaldin-khaled/GAN7
      branch: main
    build_command: npm install && npx vite build
    output_dir: dist
    routes:
      - path: /
    environment_slug: static-site
    envs:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://api.gan7club.com
      - key: VITE_STRIPE_PUBLIC_KEY
        value: pk_test_51RfHRzP623EsFG0oJiJ43PsCwsWyguGY7yoYuvMiUMMVyU019qUzMDytg7JOIx6k7EXxSOf36jTHnvbBjukMAFDy00iQcjXEOc
      - key: VITE_APP_NAME
        value: Gan7Club
      - key: VITE_APP_VERSION
        value: 1.0.0
    domains:
      - name: gan7club.com
      - name: www.gan7club.com
    # Explicitly specify this is a static site
    run_command: ""
    instance_count: 0
    # Static site configuration
    static_site_config:
      error_document: index.html
      index_document: index.html
    # Add custom nginx configuration
    nginx_config: |
      server {
          listen 80;
          server_name _;
          root /var/www/html;
          index index.html;

          # Handle React Router - serve index.html for all routes
          location / {
              try_files $uri $uri/ /index.html;
          }

          # API proxy
          location /api/ {
              proxy_pass https://api.gan7club.com;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }

          # Media proxy
          location /media/ {
              proxy_pass https://api.gan7club.com;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }

          # Cache static assets
          location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
              expires 1y;
              add_header Cache-Control "public, immutable";
          }
      } 